### ISSUE TITLE
How to use async functions with this preset?

### ISSUE THREAD

**Issue by trusktr** [christophehurpeau/babel-preset-modern-browsers#12]
Previously, I had `es2015` and `stage-0` presets, which allowed me to use `async` functions.

But now I'm trying `modern-browsers` and `modern-browsers/safari9` and that results in "unexpected token" errors about the `async` keyword.

I tried adding the `stage-0` preset alongside the modern presets, and that works, but it seems to compile everything the same as with `es2015`. For example, it compiles `class {}` syntax down to ES5 classes, but I was thinking that modern-browsers would leave class syntax alone.

**Comment by christophehurpeau** [comment]
Hello !
Indeed, to support `async` functions, you can add `stage-0` or `stage-1` or `modern-browsers-stage-1`.

It doesn't compile everything the same as `es2015`, but safari 9 doesn't supports classes, so it does transform classes. You can see all features supported in the [compatibility table](https://github.com/christophehurpeau/babel-preset-modern-browsers#compatibility-table). I can't wait for safari 10 ! =)
You can also choose to support only latest firefox and chrome.

**Comment by trusktr** [comment]
Ah, for sure. The problem is I'm making a library (as opposed to an app), so I guess I need to compile the classes then since I want it to be usable everywhere.

But yeah, I can't wait for Safari 10 either. It's going to have Proxy too, which will allow some interesting things!

**Comment by trusktr** [comment]
Turns out I will not be using ES6 classes any more anyways (for now, [because `super` is static](https://esdiscuss.org/topic/the-super-keyword-doesnt-work-as-it-should), and constructors are not callable), and I am making a tool for multiple inheritance where in [one implementation](https://gist.github.com/trusktr/8c515f7bd7436e09a4baa7a63cd7cc37) that involves method copying it simply breaks the `super` keyword at runtime unless using `eval` which loses the scope where the original method-to-be-copied was defined, and in the [other implementation](https://gist.github.com/trusktr/05b9c763ac70d7086fe3a08c2c4fb4bf) `super` works just fine but I need to have callable constructors which ES6 classes don't provide (and Proxy will make the implementation cleaner once Safari 10 is out).

The idea stemmed from my desire to do something like this:

```js
import SomeClass from './SomeClass'
import OtherClass from './OtherClass'

class Foo extends multiple(SomeClass, OtherClass) {
  // ...
}
```

where `SomeClass` and `OtherClass` may have two completely separate prototype chains.

**Comment by christophehurpeau** [comment]
You can also consider building your library for several targets with several main, allowing you to choose with webpack which one you want in the end. Faster than rebuilding all node_modules with babel !

**Comment by trusktr** [comment]
Him, I guess that would work but also multiply the size of the published package by the number of targets. Well, NPM and GitHub are free for open source projects, so I guess they are okay with that.

I can make a separate repo just for the releases on GitHub I suppose.

Sounds like a plan! :+1:

**Comment by trusktr** [comment]
@christophehurpeau When someone does

```js
import SomeClass from 'my-library/path/to/SomeClass'
```

, how does that import for the proper target?

I know how to configure it in Webpack and Browserify, but Meteor and NPM both just look at imports relative to `node_modules/my-library`.

I feel like suggesting

```js
import SomeClass from 'my-library/<target>/path/to/SomeClass'
```

where `<target>` is replaced with the actual target as in

```js
import SomeClass from 'my-library/safari/path/to/SomeClass'
```

would be problematic because then the code relies on the `≤target>` and is not portable across targets without having to find/replace all occurrences of `<target>`.

**Comment by christophehurpeau** [comment]
I advise you to do single-file packages when possible. If not, you can either export everything in the main file, or create multiple entry-points and configure webpack to go look in the right directory.

**Comment by trusktr** [comment]
A single-file package is not really always feasible, and may not help in tree-shaking. Sometimes classes don't make sense to be shipped in separate packages because they aren't intended to be standalone classes, and having them in different files of the same package helps keep code organized.

I guess really I should just write for my lowest common denominator target. I think modern-browsers and modern-browsers/safari may be that. 

How do I read the compatibility table? Do I assume that modern-browsers compiles anything that says "No" in the table?

**Comment by christophehurpeau** [comment]
Yes: "No" or the version is not the stable version

**Comment by trusktr** [comment]
Gotcha! Thanks! Would be nice if that was more apparent somehow.
