### ISSUE TITLE
object-rest import failing in webpack

### ISSUE THREAD

**Issue by ro-savage** [christophehurpeau/babel-preset-modern-browsers#13]
`object-rest` appears to be failing the import for my webpack build. I had a look at the codebase here and couldn't see any issues. So not sure what is going on.

Example of failing code

```js
    loaders: [
      {
        test: /\.js$/,
        include: PATHS.src,
        exclude: /node_modules/,
        loader: 'babel',
        query: {
          cacheDirectory: true,
          presets: ['modern-browsers', 'modern-browsers/object-rest', 'react'],
          plugins: [
            'react-hot-loader/babel',
          ],
        },
      },
```

gives the error
```
ERROR in ./src/views/collectionItems/collectionItems/CollectionItemsReducer.js
Module build failed: SyntaxError: Unexpected token (61:10)

  59 |       return {
  60 |         collectionItems: {
> 61 |           ...state.collectionItems,
     |           ^
  62 |           [action.payload.id]: action.payload,
  63 |         },
  64 |         defaultOrder: [...state.defaultOrder, action.payload.id],

 @ ./src/views/rootReducer.js 11:30-97
```

if I update the presets to `presets: ['modern-browsers', 'stage-2', 'react'],` it works fine.

Any thoughts?

**Comment by christophehurpeau** [comment]
Sorry I missed this issue !
`modern-browsers/object-rest` is an additional preset to make `babel-plugin-transform-object-rest-spread` works, you can see [the issue on babel](https://github.com/babel/babel/issues/4074)
So you need both `modern-browsers/object-rest` and `stage-2`
