### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by mroderick** [christophehurpeau/babel-preset-modern-browsers#16]
In https://github.com/christophehurpeau/babel-preset-modern-browsers/commit/ade31a8a1109c3c2da948c418ca22f82cca2ce62 new dependencies were added:

* `babel-plugin-syntax-trailing-function-commas` 
* `babel-plugin-transform-async-to-generator`

However, they are not mentioned in `package.json` or `yarn.lock`, causing the `8.1.0` release to fail for users.

**Comment by christophehurpeau** [comment]
Thank you for reporting ! Fixed in 8.1.1
