### ISSUE TITLE
Maintain the changelog

### ISSUE THREAD

**Issue by gajus** [christophehurpeau/babel-preset-modern-browsers#2]
Please maintain the changelog, https://github.com/christophehurpeau/babel-preset-modern-browsers/blob/2d2e3fce52c797b4aa3616aa086791f06ff30f73/CHANGELOG.md.

The module has been bumped to v3 with no indication of what has been changed.

**Comment by christophehurpeau** [comment]
Yes fixed it ! https://github.com/christophehurpeau/babel-preset-modern-browsers/commit/cfbed40de86b1213c814b43b0ac4568d143555f8 
Sorry
